### PR TITLE
Add a link to a wiki page for newcomers

### PR DESCRIPTION
**Pull request by ulysses4ever**

### CODE REVIEW

**Comment by fikovnik** [comment]
Would it make sense to actually have the _New members_ link point out straight to the wiki?

**Comment by ulysses4ever** [comment]
@fikovnik good idea! On the one hand current page is very uninformative. On the other, as a matter of politeness in web design, I prefer not to send users to other web sites right from the menu. 

Any other wants to make a point? @julbinb @kondziu

**Comment by julbinb** [comment]
I would either add a link to the wiki as suggested by @ulysses4ever, or have the _New members_ link pointing to a _New members_ wiki page, which we don't have yet. For now it's easier to do the first, I think.

**Comment by fikovnik** [comment]
What do you mean by the _politeness in web design_? (I know nothing about web design) :-)

**Comment by ulysses4ever** [comment]
@fikovnik nevermind, I made a change according to your proposal

**Comment by kondziu** [comment]
I like how it works now. It's straightforward.

**Pull request merged**
