### PR TITLE
Added a book chapter

### PR DESCRIPTION
**Pull request by fikovnik**

### CODE REVIEW

**Comment by ulysses4ever** [comment]
BTW, do we have any policy on adding papers to the pubs page? E.g. I had a paper written with my student a while ago [which have just been published](https://link.springer.com/chapter/10.1007/978-3-319-71734-0_8). Does it make any sense to add it here? @janvitek?

**Comment by fikovnik** [comment]
I don't think we have any. 

I wrote that chapter while still in France, but it took quite a while for the book to be published. I got the notification in december last year. It is with my FIT affiliation so I though it would be good to exhibit it here. Anyway, we can always remove it.

**Comment by ulysses4ever** [comment]
So, the same story for me, I guess. I don't even have the FIT affiliation in there…

**Comment by fikovnik** [comment]
I guess one author should have FIT affiliation?

**Comment by ulysses4ever** [comment]
That is exactly what I was asking about. Well then, next time… Thanks!

**Pull request merged**
